"""rename address

Revision ID: 55e55a847acd
Revises: b52dc6df4d8b
Create Date: 2024-04-05 12:19:06.047595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e55a847acd'
down_revision = 'b52dc6df4d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')

    # ### end Alembic commands ###
